"""empty message

Revision ID: e81f0f13946a
Revises: c6e290ef67c3
Create Date: 2020-12-04 14:27:26.690931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81f0f13946a'
down_revision = 'c6e290ef67c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_type', sa.String(length=250), nullable=True))
    op.execute("UPDATE document SET doc_type = 'PDF'")
    op.alter_column('document', 'doc_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'doc_type')
    # ### end Alembic commands ###
